### ISSUE TITLE
SQL errors when inserting a new paste

### ISSUE THREAD

**Issue by Shushandr** [RaJiska/BeyondPaste#2]
```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column beyondpaste.paste.autodestroy at row 1
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column beyondpaste.paste.deleted at row 1
```
![изображение](https://github.com/RaJiska/BeyondPaste/assets/148656348/b6820065-8049-43d1-ad38-1708bb03bbe0)

**Comment by RaJiska** [comment]
Hi, could you provide a cURL of your request?

**Comment by Shushandr** [comment]
No, I don't know the difference between cURL and URL, and `curl` is command line utility.

**Comment by RaJiska** [comment]
Could you try to replicate on paste.rajiska.fr ? If the error doesn't happen, it's most probably due to version of the database or PHP interpreter.

**Comment by Shushandr** [comment]
I didn't understood the word "replicate". What I am doing is just try to create a paste on my local machine. paste.rajiska.fr creates a paste. My local machine doesn't. "Replication" is a term from area of databases, but I can't see the database of website, because don't know it's settings.

```
# php -v
PHP 8.2.11 (cli) (built: Oct 22 2023 07:31:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.11, Copyright (c), by Zend Technologies
```

```
# mysql --version
mysql  Ver 15.1 Distrib 10.6.14-MariaDB, for Linux (x86_64) using readline 8.1
```
My hypothesis that it's locale, what is different.

**Comment by RaJiska** [comment]
By replicate I mean replicate the issue. I have actually been able to replicate while refactoring a bit to use Docker. I will publish a docker version that runs so that it can be easily deployed.

**Comment by Shushandr** [comment]
"reproduce"? I am using Gentoo Linux, and my goal is to deploy some application natively (Gentoo have it's own mechnism `webapp-config`). So It will be useful to me to have a bit more textual explanation than docker scripts.

**Comment by RaJiska** [comment]
Updated the codeabase through https://github.com/RaJiska/BeyondPaste/commit/aecbb54bb1de241b5b1d6f53a22737b12d072c2f. This should fix the issue you are having while having a default support for Docker which you can setup yourself by following instructions [here](https://github.com/RaJiska/BeyondPaste#installation--docker).

As a side note, the issue you were facing was fixed through changes made in [this file](https://github.com/RaJiska/BeyondPaste/commit/aecbb54bb1de241b5b1d6f53a22737b12d072c2f#diff-61850cde9400be4ce96fe9646401f309657bbc0cdcf6d2a27abf5087987a25c1).

> So It will be useful to me to have a bit more textual explanation than docker scripts.

Through docker you have a full end-to-end installation process of the tool which should allow you to set it up on bare-metal if you wish so. I'd be happy to help if you have more precise questions though.

**Comment by Shushandr** [comment]
I saw [in code](https://github.com/RaJiska/BeyondPaste/commit/aecbb54bb1de241b5b1d6f53a22737b12d072c2f#diff-4b0f9af92c92af55be512d284d7f318a4e591c3c07348d99c0005ceb432e692eR21) that you changed paths from relative to root paths of webserver. [`webapp-config`](https://wiki.gentoo.org/wiki/Webapp-config) assume that it's possible to deploy application into any virtual directory under site root. I will create a new issue, when I will be able to get to that stage.

UPD:
I successfully installed and run the project in docker. (But will try to install it in Gentoo Way anyway - «Extreme Configurability: Gentoo is known for its extreme configurability. The source code is compiled locally according to the user's preferences and is often optimized for the specific type of computer. This level of customization is a hallmark of the Gentoo way»)

**Comment by RaJiska** [comment]
>I saw [in code](https://github.com/RaJiska/BeyondPaste/commit/aecbb54bb1de241b5b1d6f53a22737b12d072c2f#diff-4b0f9af92c92af55be512d284d7f318a4e591c3c07348d99c0005ceb432e692eR21) that you changed paths from relative to root paths of webserver. [webapp-config](https://wiki.gentoo.org/wiki/Webapp-config) assume that it's possible to deploy application into any virtual directory under site root. I will create a new issue, when I will be able to get to that stage

Yes, had to change to the root as it was causing infinite redirections and paths not being properly resolved. This should still work in a virtual environment as this path would direct to the document root of your webserver virtual env (in this instance with the current setup, `/resources/external/bootstrap/css/bootstrap.min.css` points to `/var/www/html/resources/external/bootstrap/css/bootstrap.min.css`.

> I successfully installed and run the project in docker. (But will try to install it in Gentoo Way anyway - «Extreme Configurability: Gentoo is known for its extreme configurability. The source code is compiled locally according to the user's preferences and is often optimized for the specific type of computer. This level of customization is a hallmark of the Gentoo way»)

Sure, you can try the Gentoo way, not too sure what more customisation you can have compared to docker though as you could literally have a dockerised Gentoo.

**Comment by Shushandr** [comment]
New version of code works better, see also https://github.com/RaJiska/BeyondPaste/issues/4#issuecomment-1784808470
